version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    environment:
      - REACT_APP_FOODLIST_BACKEND_URL=http://localhost:8000/api/

  backend:
    build: ./backend
    ports:
      - '8000:8000'
    volumes:
      - .:/code  
    depends_on:
      - db
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: