apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: foodlist-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api # Backend service
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 8000           
      - path: /
        pathType: Prefix
        backend:
          service:
              name: "{{ include 'frontend.name' . }}"
              port:
                number: {{ .Values.service.port }}
