name: Docker Build

on:
  push:
    branches: [ main, master ]

jobs:
  Build-Docker-Images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker backend image
      uses: docker/build-push-action@v2
      with:
        context: ./app/backend
        push: false
        tags: backend:v3.0

    - name: Build Docker frontend image
      uses: docker/build-push-action@v2
      with:
        context: ./app/frontend
        push: false
        tags: frontend:v0.12